#!/bin/bash

DOTFILES=$HOME/dotfiles
BSTD=$DOTFILES/bootstrap.d
source $BSTD/utils.sh

init_brew() {
    # brew exist?
    if [ -x "`which brew`" ]; then
        log_warn 'brew already exists!'
        setup_brew
    else
        install_brew
        setup_brew
        post_setup_brew
    fi
}

install_brew() {
    log_echo ''
    log_echo 'Install homebrew'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

setup_brew() {
    log_echo ''
    log_echo 'Run brew bundle'
    brew bundle --file=$DOTFILES/Brewfile
}

post_setup_brew() {
    log_echo ''
    log_echo 'Run post brew bundle'
    # change login shell to zsh
    if [ -f /usr/local/bin/zsh ]; then
        log_info 'change login shell to /usr/local/bin/zsh'
        sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells"
        chsh -s /usr/local/bin/zsh
    fi

    # create symlink for diff-highlight
    if [ -f /usr/local/share/git-core/contrib/diff-highlight/diff-highlight ]; then
        log_info 'create symlink for diff-highlight'
        ln -s /usr/local/share/git-core/contrib/diff-highlight/diff-highlight /usr/local/bin
    fi
}

setup_dotfiles() {
    log_echo ''
    log_echo 'Setup dotfiles'
    $BSTD/dotfiles.sh
}

setup_rbenv() {
    log_echo ''
    log_echo 'Install Ruby with rbenv'
    $BSTD/rbenv.sh
}

setup_pip3() {
    log_echo ''
    log_echo 'Install Python libraries with pip3'
    $BSTD/pip3.sh
}

init() {
    log_echo ''
    log_echo 'Run init'
    ask_sudo_password
    init_brew
    setup_rbenv
    setup_pip3
}

update() {
    log_echo ''
    log_echo 'Run update'
    setup_brew
    setup_rbenv
    setup_pip3
    setup_dotfiles
}

usage() {
    log_error >&2 "Usage: $0 <init|update|brew|dotfiles|rbenv|pip3>"
    exit 1
}

case $1 in
init)
    init
    ;;
update)
    update
    ;;
brew)
    setup_brew
    ;;
dotfiles)
    setup_dotfiles
    ;;
rbenv)
    setup_rbenv
    ;;
pip3)
    setup_pip3
    ;;
*)
    usage
    ;;
esac

log_echo ''
log_pass "$0: Finish!!"
