# ~/.tmuxinator/default.yml

name: project_name
root: ~/dev/

pre:

windows:
  - zsh:
  - console:
      layout: even-horizon
      panes:
        - console:
          - rails c
        - server:
          - spring stop
          - pgrep mysql || startmysql
          - while [ ! `pgrep mysqld` ]; do sleep 1; done;
          - ([ -f tmp/pids/server.pid ] && (kill -SIGKILL `cat tmp/pids/server.pid`; rm tmp/pids/server.pid))
          - foreman start
  - git:
      layout: even-horizon
      panes:
        - gitsh:
          - gs
        - guard:
          - guard
