# ~/.tmuxinator/default.yml

name: project_name
root: ~/dev/

pre:
  - (pgrep mongod || mongod > /dev/null &)
  - spring stop
  - ([ -f tmp/pids/server.pid ] && kill -INT `cat tmp/pids/server.pid`)
  - ([ -f tmp/pids/server.pid ] && rm tmp/pids/server.pid)
  - ([ `pgrep weechat` ] && kill `pgrep weechat`)

windows:
  - zsh: while [ ! `pgrep mysqld` ]; do sleep 1; done && rails s > /dev/null &
  - editor: vim .
  - git:
      layout: even-vertical
      panes:
        - tig --all
        - gs
  - console:
      layout: main-vertical
      panes:
        - rails c
        - (pgrep mysqld || startmysql) && rails db
  - test:
      layout: even-horizon
      panes:
        - DISABLE_SPRING=1 guard
        - tail -f log/test.log
  - log:
      layout: even-horizon
      panes:
        - tail -f log/development.log
        - sleep 1 && pstree -s rails
  - chat: weechat
  - mail: mutt
