# ~/.tmuxinator/default.yml

name: project_name
root: ~/dev/

pre:
  - pgrep mysqld || startmysql
  - spring stop
  - ([ -f tmp/pids/server.pid ] && kill -INT `cat tmp/pids/server.pid`)
  - ([ -f tmp/pids/server.pid ] && rm tmp/pids/server.pid)
  - ([ `pgrep weechat` ] && kill `pgrep weechat`)

windows:
  - editor:
      layout: even-horizon
      panes:
        - vim .
        - la
  - git:
      layout: even-vertical
      panes:
        - tig --all
        - gst
  - console: rails c
  - db: rails db
  - server: rails s
  - test: guard
  - log: tail -f log/development.log
  - chat: weechat
